### PR TITLE
Add params argument to solr requests

### PR DESCRIPTION
**Pull request by Luxas98**
This change allows to specify custom request url parameters for solr requests (like omitHeader, commit, etc...), so user is able alter defaults. Original behaviour is not altered. Add extra tests for add/search with params.

Let me know what you think and if something should be changed.

### CODE REVIEW

**Comment by Luxas98** [comment]
it's mainly about line 53 in search.py, params where not propagated at all.
Other changes like params={} to params=None is enhancement check: https://docs.quantifiedcode.com/python-anti-patterns/correctness/mutable_default_value_as_argument.html

you should never use mutable types (dict(), list(), ...) as default values in declaration (declaration of arguments is executed only once so you will endup with the same object in any function/method call). But it's mostly about the params propagation to _get_response to be able to override default parameters (for example omitHeader) and add more if needed. 

```
-        resp = self._get_response(path, method='POST', params={}, body=body)
 +        resp = self._get_response(path, method='POST', params=params, body=body)
```

**Comment by relwell** [comment]
Okay, that makes sense. You will probably want to add in a version bump commit if you'd like to get this feature quicker.

**Comment by Luxas98** [comment]
Cool, should I just bump __version__ = "2.4.0" to 2.4.1 or something?

**Comment by relwell** [comment]
Works for me!

**Comment by relwell** [comment]
@Luxas98 quick reminder you'll need to add a version bump before I merge this -- thanks!

**Comment by Luxas98** [comment]
Thanks for reminder :-) completely forgot about it. Cheers.

**Pull request merged**
